apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csearch-mars-core
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: fastapi=registry.s8njee.com/csearch-fastapi,scraper=registry.s8njee.com/csearch-updater,frontend=registry.s8njee.com/csearch-frontend
    argocd-image-updater.argoproj.io/fastapi.update-strategy: digest
    argocd-image-updater.argoproj.io/scraper.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/s4njee/csearch.git
    targetRevision: fastapi-api-rewrite
    path: k8s/mars
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
