apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csearch-mars-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/s4njee/csearch.git
    targetRevision: optimize
    path: k8s/mars-db
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-cnpg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
