apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csearch-freya-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/s4njee/csearch.git
    targetRevision: freya
    path: k8s/freya-db
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
