apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csearch-mars-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/s4njee/csearch.git
    targetRevision: fastapi-api-rewrite
    path: k8s/mars
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
