apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-dev
spec:
  # Runs at 1 AM UTC every day
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: congress-nfs
              persistentVolumeClaim:
                claimName: congress-nfs-pvc
          containers:
            - name: csearch-updater
              image: registry.s8njee.com/csearch-updater:latest
              imagePullPolicy: Always
              command:
                - /app/entrypoint.sh
              volumeMounts:
                - mountPath: /srv/csearch/congress
                  name: congress-nfs
                - mountPath: /srv/csearch/data
                  name: congress-nfs
                  subPath: data
              env:
                - name: POSTGRESURI
                  value: postgres-dev
                - name: DB_USER
                  value: postgres
                - name: DB_PASSWORD
                  value: password
                - name: DB_NAME
                  value: csearch
                - name: RUN_BILLS
                  value: "true"
                - name: RUN_VOTES
                  value: "true"
              resources:
                requests:
                  cpu: "250m"
                  memory: "512Mi"
          restartPolicy: OnFailure
