// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package temp

import (
	"database/sql"

	"github.com/jackc/pgtype"
)

type InsertBillParams struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pgtype.JSONB
	Actions       pgtype.JSONB
	Sponsors      pgtype.JSONB
	Cosponsors    pgtype.JSONB
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}
