apiVersion: v1
kind: Service
metadata:
  name: csearch-frontend-dev-lb
  labels:
    app.kubernetes.io/name: csearch-frontend-dev
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: csearch-frontend-dev
  ports:
    - name: http
      port: 4200
      targetPort: http
  type: LoadBalancer
