apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csearch-congress-data
  labels:
    app.kubernetes.io/name: csearch-updater
    app.kubernetes.io/component: scraper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
