apiVersion: batch/v1
kind: CronJob
metadata:
  name: csearch-goscraper
  labels:
    app: csearch
spec:
  schedule: "@midnight"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: csearch
    spec:
      template:
        metadata:
          labels:
            app: csearch
        spec:
          nodeSelector:
            node: worker1
          restartPolicy: OnFailure
          containers:
            - name: congress-goscraper
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              image: 10.0.0.3:30252/scraper
              imagePullPolicy: "Always"
              volumeMounts:
                - name: temp-data
                  mountPath: /congress
          volumes:
            - name: temp-data
              persistentVolumeClaim:
                claimName: csearchpvc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: congress-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/temp/congress
    server: 10.0.0.3
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csearchpvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  volumeName: congress-pv
  resources:
    requests:
      storage: 50Gi