apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s/archives
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
