apiVersion: v1
kind: Secret
metadata:
  name: registry-s8njee-pull
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.s8njee.com": {
          "username": "replace-me",
          "password": "replace-me",
          "auth": "replace-with-base64-of-username-colon-password"
        }
      }
    }
