---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-api-openai
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgAF3pP2s/rRvSAosxKw85MKcpIGU0CBQou0+aAVVSobSefm9b+z+CXJcJhZ/j3qXgJvjSIw9Es16+wTK70nkjZ+kAl1kzCefJf/ddBAbS/crYibxV8jUJeGesYGTGJ+xdNF/dBwx8wrHa8pzf3j1yh3JnDPt5kQQ/oHAk61wPTbA3L8g+iX2Ki3PDj/UrqRPIQcfHQRqzY1HbBeTOODocShyvvKqD+dSeFoltezZgJaTwlER4Nk2gV2gQ4QRJhhhEXzcADAdt72PnOsoPS9Vw8oaQ0ZwowDbz/ebdLGlNxlT694GTcrMgiqcRsF2kTF87s7BTR2xIuOBzw3r4Q97yIce+yZz1WcfUVYCGxOay0eshLhU7aUJ4OQqY1b1wn+HFufkK6Tl96uq+JjJccubXTq927i62ViLEGMDaesHKxtOrfVUHGbEeCElomfKsP34yS2sHc56Qfsgog9rhg7Q4/RSMJkPSH+Cc7RkCg4EiSo8A7mdq6vy20i+XZ6o6j34a8hHIGOvPI9CxE8yd4DnDXY/HFQzJjUTI3IxpEfvpBlXIoCcAgq0+KSMdR097GvmHiZKsyLUbCSzs3ZVEUrfo9TFpg+pVXh3w7ndJ+XBDOWPd9qot8g3LRUTmZEaT02aPGtmMySRXhTbbCFMlLkkpc7cKyRylhu1aytOSFZ7slUiMB2lzB3eyTeEl7nt21d2tlKyhjcXnGd6RluyUtq/nU5cw4wAvLOVrhFmsxug06dwYvdDeWpWJS6Q9DobRRjIQt4G3Dt7cyAlG+C71jb/Mk6Q+53hYExtDZ7GWL9T9CZ/9AEDO1j6JpHYDJO/VpD4gVh3JSBpEnVgyN2yPXSjRc9O20OehpWoE14IJ9khV+BhN5raHd1l200ohALlZusBaBImZXcqwtVoe48e4pf2fVcZ1rqMg==
  template:
    metadata:
      name: csearch-api-openai
      namespace: default
