{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "csearch-api-openai",
    "namespace": "default"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "csearch-api-openai",
        "namespace": "default"
      }
    },
    "encryptedData": {
      "OPENAI_API_KEY": "AgBMuJDA2J3W0xOLgHu+2vxyFZcSGzcg4uhLAN60gqIZu4q0d8i2c82qjMaejhD503cowD46p9UZKR1Uf3KVT7PbflJSSXivHJaK7wtMI3ExZRM+dfxN73A4lURUOuDikZrScka3sHBEX8rHaZEr+e6zI5I5WQLN7X2wxBI6s1l/DKglzMZbk8Cewke+NZ0ismUvYSND2CaBA9XrzY58DNr26xqLnCb8kTpgNaijm4MEwK8s0f88zu1GiHj/0VfkTo09YShJlEsHPauXnf/W2gDwTXxWT4wsNiChQRETNhLbrsZ1Wqn8gEyMnO4TDxuBrhNLJMVcQZZpz6OU1FX39lKSZgO9XQ3DEfPJp2AIsLpe+cDHNDwU6J9qVU3jpqjxjzAOPJ2DCebmYuCrMXbnha9d0Iz0pKfnHk+yVgqN0JEsKjZQPqgwzEtxS0dfZqG0/azrJRZP/8YVBYDc3Ux5ysQGwqRvmbfZTtL21TkngZjjgy/KICgDdtuAdBwLgehQ58NN8kuKovCyHckDcQSiP6eFgAgMqpKN4G4UPJlNpRvfbgOseXSsjA7YpyyEzk3O1JvUjK80ahPGqCP+KHaxq4yMnYXMh/Wv2q+MR/tBO7NQGM8eUpAOUk4ekFjqRC9aYtN3lQTqcXUgFXXOphTZtp/Sb0ajrAUp6sriEGDiKF2ZT36A6po+5b8RRdaHfk2IjUuOHKPN8g2LOFn1+rGM52a3Kk5x76OyNWAV518be/rCUmZ3u1S8WgaZXWRtO5jktlHnej0njt7dTTxbwwhoj28qzwqkbXwzSTRZC+2JRJL7TSlKNl7uFUwbXLHlkfoDN+ZnjpdfConZFUoyoPhVJPYl3E2r5yDc5BHCZoHZDI+yZbDqEx1Op/3bKEbuh1AbeCJJB3ylodsnOvVSpuFsEOQhuHTQaA=="
    }
  }
}
