---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-cloudflare-deploy-hook
  namespace: default
spec:
  encryptedData:
    DEPLOY_HOOK_URL: AgBa1MskFJmYaKD6DRQyxvkd57zMQWvoJgic0aOCzgnx4id3EDP6ePZ7Ogvp4W8rP3yzm2RQz/aOXGOWPuph52OpWOb3te6yczfuz+22hced1aZCC+6VjyEj6fjATfgIBm4IcfRnSOCkYT9CYEGvXdTkJ9WLxvGv9dApiBgm+4cC2PS8a72Zx/+5YYpfdDcyYCYAen1xp0OQeBse8VdGZGl9Zk30krSEtCmkE1JYyp/l8gvf2rF6UUExi9ShZCwsxEsT1uuI5heuXVStXH+3xWwrTFPGFAvms7uyp5fx+UAbeLCgEm0jDZtI6mp1NNSvqhE5M5BwHD1ErYVDoFwTH9em/jyKbcOOCDwjl6YeVTLJ0ofdg4a2rUIgL5oPMhxnnJrxnyD6zFiGWFqnaXb0FOKpTupN7eZEyPnpmDD0ctkxC55k8IqfKOhTQVWZ1kUe/9zwuv0etVwYyBjxzr/X0NpPEQhjlb4NzPq+MkDluZQvUnNdiBJQVt2EiIPyaz+cgyqwtfDBZw2ldENR0v5YiLm2MQKlSheEoow7WXj7c3aVlqWsdtjOm7W8J43PzCMT1+uOSzOuzjSLXJv/uxsd5EE6a9p10AOOXGvQPRXSs/6V7uTt+Huv8hz8rI+fUqpN/UePZ27Rx2+VGXTtlxDgmTiQixPAFeU/9JLEaRB4EL63cP4cgDmzF1+ZnZCLSaqi5kQDyS35ERPnn1vy/I2760LBQRyslheqE0zTppsEcKs1kWNEJ4CjtcROjgtXYEFITNMWDQSZ3F4OGWLdx1bc1W+lHYeGsFRl+fdz0s5L+AZUVfkokSaNFHz7uip5GuPasibRvCIulw==
  template:
    metadata:
      name: csearch-cloudflare-deploy-hook
      namespace: default
