{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "csearch-cloudflare-deploy-hook",
    "namespace": "default"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "csearch-cloudflare-deploy-hook",
        "namespace": "default"
      }
    },
    "encryptedData": {
      "DEPLOY_HOOK_URL": "AgBY3ZiXkSdZTObpK25eXznsQM3/PxqVXHJIvDvMsG1BqOT2/Pz2xn6rsdva1+24LNlsYhuVm2SOzSnIuXDOCF4y03k+HNqhnGCYb/SS2IGGDp9PAGkdmMsOAzfAWcZWayJmOK4hAncmh/XKMjCb6Bzjb9HUfrhixeRPMKUFBjumVLAZogtd3WGDmkKVh8i/UDkuEAkjLJ6dNiP6idFwP/BMhYMITeZyywc+9nvNgCdieD2OIvtSKeas1CYbQx/TSR0fIdpOH1jec9XuoRkqlTwtIRjMqyo54y83t6UL9Nzih3xVIgvulDV12BvQlYv/nW4wjAvYbvDUn2gcAa/23+2isc708CimAoamMmaSKdMwChm79xr4/YyPqLL+VN7ZwF9vrKL1HjYHiOPNLY5ksGJ+liz/ojGAVzSulnPwAEqqQqGIlf2O60ffT1+mX4qR6jIrtAb4d+iW9thY8RnEOpNvd/KS52XrBa+kR3FVGnz5ab7VqkM629ebuGfogK5tcx4HUbUrpJ+WuNgOuBbK9Seighk6zguu19vNg/0dThwdCIOOqUQEWW5DtOucmBB83I1b3+IE0WeqeO8fvFpHYjEiREEpXEdd+8AFLmt1zaO2bjnT5OKsbb4CUH3ycUD13HQMMUU8va3OFrjWu/f7SWgMAY15MM8kzvTyVtQ4sU5Bqhff1EsOX7zkOVHWWCuibhc3iNdjbn9bmBYcsnSCUGo4aZo0kxZdemiOy1EECW6JEowvZHhJJ8IIZk2MqbvX0Bro1VB3RNKrIlBxvlweQL5uSEGOoE6YNMqwBAolVJMr40QXx/p9+CDhi42TFjkPk+Ml0YaN9Q=="
    }
  }
}
