apiVersion: v1
kind: Service
metadata:
  name: csearch-log-collector
  labels:
    app.kubernetes.io/name: csearch-log-collector
    app.kubernetes.io/component: logging
spec:
  selector:
    app.kubernetes.io/name: csearch-log-collector
  ports:
    - name: http
      port: 8080
      targetPort: http
