// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package csearch

import (
	"database/sql"
	"time"
)

type Bill struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
	SearchDocument    interface{}
}

type BillAction struct {
	ID               int64
	Billtype         string
	Billnumber       int32
	Congress         int32
	ActedAt          time.Time
	ActionText       sql.NullString
	ActionType       sql.NullString
	ActionCode       sql.NullString
	SourceSystemCode sql.NullString
}

type BillCommittee struct {
	Billtype      string
	Billnumber    int32
	Congress      int32
	CommitteeCode string
}

type BillCosponsor struct {
	Billtype            string
	Billnumber          int32
	Congress            int32
	BioguideID          string
	FullName            sql.NullString
	State               sql.NullString
	Party               sql.NullString
	SponsorshipDate     sql.NullTime
	IsOriginalCosponsor sql.NullBool
}

type BillSubject struct {
	Billtype   string
	Billnumber int32
	Congress   int32
	Subject    string
}

type Bills100 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills101 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills102 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills103 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills104 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills105 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills106 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills107 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills108 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills109 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills110 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills111 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills112 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills113 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills114 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills115 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills116 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills117 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills118 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills119 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills93 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills94 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills95 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills96 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills97 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills98 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Bills99 struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsDefault struct {
	Billid            sql.NullString
	Billnumber        int32
	Billtype          string
	Introducedat      sql.NullTime
	Congress          int32
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullTime
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullTime
	BillStatus        string
	Statusat          time.Time
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Committee struct {
	CommitteeCode string
	CommitteeName sql.NullString
	Chamber       sql.NullString
}

type Vote struct {
	Voteid         string
	BillType       sql.NullString
	BillNumber     sql.NullInt32
	Congress       sql.NullInt32
	Votenumber     sql.NullInt32
	Votedate       sql.NullTime
	Question       sql.NullString
	Result         sql.NullString
	Votesession    sql.NullString
	Chamber        sql.NullString
	SourceUrl      sql.NullString
	Votetype       sql.NullString
	SearchDocument interface{}
}

type VoteMember struct {
	Voteid      string
	BioguideID  string
	DisplayName sql.NullString
	Party       sql.NullString
	State       sql.NullString
	Position    string
}
