---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-cloudflare-deploy-hook
  namespace: default
spec:
  encryptedData:
    DEPLOY_HOOK_URL: AgCSEBM6P1256woxkFN7FjIHAAtvltxa+Al7J8/OdBKO4n+bQJg9THk+Me1qUzVsU1Lus54eXmVfrvPLU8CVRsNz5abcMa0CzakoD/KPlKrrU4XnvLPsciYkQHjbVo1rJk3dBkS1wWeM6/ROsKgYjm97moPWju444aipFqm7sTyPOFvELXSUxAl2xU0vxLGRvUWIWZZ6LVL/AEnddsKQVugZRM/B4pUbSNzf7KzjVMYdy8mlGFL1r/SCkd/nrHFXGL8lO9HCY4pMefKUw+VWqW4PhKwycuLmlgTo2uOaQ/gIAwmboqRI+/O5nlP5givUYUJoKUi71njlstiKFrhQROZejzzcIoasWjU0JsjDFawIzYV//w198UuIrPOE5nDmCf2bonctcDB1meAP4WgQ8rZM7puk0f0h+NOW/acz+gzIvrcb9CyHpawfWioDmsX0XPdpws74ePEtb6/d9mzXjfuu5iewskRFikeCkLoMACCIEEvllYIpQV6xQaMFk3FCdO/yvQpQrQ8E8qCmL1muYypBnO+5H8d0VOpBa12UDlh2Pr9sIk7mTn42It1vT4qNlZsJG+mRGx4yRc/46xyEL5y3IDzNDdr1RWfDp23gTeRkVrit7zMfxFSGbxw5qA/TIohVWMkrQ3Dgz5rRFz9RjZrAMwtRIKKANXN9gtMP8uicZriNh1ANK14HMSD0dReFrstcdy8Q4YUoX7MkxzLBzgQ2lknX24e5Fq//z2Kbxtm2F5NsnFOqIIwkoA+PKG3+uvj9A/0epTQjkqXOJn8LFvydhGPm4aaz5DLIMbwko5XNQcUA6WcoiS/JSs8OXkIkElLFZwvHLA==
  template:
    metadata:
      name: csearch-cloudflare-deploy-hook
      namespace: default
