---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-api-openai
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgBAL7IXEoEeWXPtyJj90m1qTZsOqnnKwhAk8KeVrNN+Gqn9YpB94KKwZqYI0BHv+CT18Z2CvjsefY+qLtOw8GDm/psROLlfQ1ix4Zsz6PjOP7HeC2XHHLGPxlU5lHhOpnYRTb4uDtdpQ/AaAYkBZFVpqllAQ9LscVTDM41cLTJ2+BUecFl+EVhppbIpYWDCQUW2biFeNobhHcVB0uXSZhPmqheeI8vt9nXIWDtMKH8/9i7QfCRLyOihC8Bh8+zSIMKor68MaknicCe9HbG2ftLTg5etZEhrXtQVZvXED2ucJVx8cSOfObBKCrwtYjoTcoGtOss0ZvrhxPRJQPyBp/gNrIWLwvMIroQxU9jolt/fcpmmmDAQ8FEk8r4ooWhTXYvgYtHdfc/J3d9rzTDc+YR/iPVJotV54aH6z2nhY1A9ULwjuOZbhyaHF/ndSTAZvcVmm0qrwrAs7Ef/8mOVNlYRpYERMwq5UMv/l+c8q2ZhSHBMSXCv2XvsqyWWMZhHoTdpHFo4d4FdmX7zXvMYcBQ03iPR8sWLT5xuz3PfNx/5eLKJYmYFYHOWje7VLETn2E9NY64ACPPahfCPunFl2yt9KI1UVENJCfvuM1LsB+nAV+IxMKoASFT5RKu5BvJVENnuDJb/ifgeuGix4L8kpiSNZ7RILsoppYq1ZdAZQv1qV/J/9ih2Vwdhx0X0RPB5XLMchDAHNcSHmQKraA==
  template:
    metadata:
      name: csearch-api-openai
      namespace: default
