---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-api-openai
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgAD17l/Ge57Rr8NLZXZl90PbIn9k+DmCrx2W7MXdk28Vjrra67/KkVAdRf3OYDsINjxrZTXgF0VwyLtZJ5X4/oq1EIwHlhRnR/j79dQCeD7Ka5I7hpq/cBwUmYbrlcAB0eQOrNqHwcgiWEz2sOeZoWoQGnuBRTgqsFjDIAzgF9j71pXysEEE5mNxpAI1ycwN8cJNO6Fm4gzAvTRRQo2sFLJXRTIN7xEdlfqGqAJJDRNaGQwl0SCARpAqlNSOx3N++qu3OXQV1s6ahf7JxArALY11qIJZnmgwvgNGX43ARchF2sUTgtweywBEyCLW2lUqP69RoHL+QktogUBvYL4fklvo7cP50ZZWoqkk/W9u1Xv36spJwpM7en5cPdt6JLHopfi5xcPP+GXTHS2DmZKLT8ZL1MYpeR8Hfq+n9lruV8o+HhfFmzmOAPxuRMKFfTTZDLq8r/IfaoOm3zfOIVd9qnQOkFvy27mvfwnOiMYQaVnH4qS4rDA3Kp3dYTtHGHsds9ExjH+UnlY6sxRJTPdt3P0wBa/tnFzJ8WfDB6uTuHigJX69LFicVwY+vrtg7K/ArNNBR63N01UNtGd3UAFMOjZlKNKUi/a+QvM4sApoyiFjui1A8VxA0E9Pmt6x3Gk3V6dr5DOV2npTPsdqbGKVcIkwgjpxvYo8NamsH9sEqc3jSTf7NdJgltIedAhwNih+lIdXfiYzgAUDgzxY52xuvkiPOOvG6yIBJgs6jMgV6ceI1kC/00CJw4/7ujVuRpcHWwA8bTCSVl9AOAaEEaT2E1kN070++B2irHtCYNJEGvwmtB3wLGuVIiy88yIo2pqFeEXfEalYr89jDMBvmyFDFRe8c3jgkFQBHPtOC3ZxZMiDz5Ggbck0sKmRAng/C6H6JAAKK5sur5FzmEoVLc1hCrH6+3d6A==
  template:
    metadata:
      name: csearch-api-openai
      namespace: default
