apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - api.yaml
  - api-ingress.yaml
  - semantic-warmup-cronjob.yaml
  - mcp.yaml
  - mcp-ingress.yaml
  - csearch-api-openai-sealedsecret.yaml

images:
  - name: registry.s8njee.com/csearch-fastapi
    newName: registry.s8njee.com/csearch-fastapi
    newTag: 8e74e595076d940bd3f897a03ae2f4a11d2a13e8
  - name: registry.s8njee.com/csearch-mcp
    newName: registry.s8njee.com/csearch-mcp
    digest: sha256:236026450ba19949009d68807c0be975be1018e4d9c3bdb473946ab9acc9d30e
