apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - api.yaml
  - api-ingress.yaml

images:
  - name: registry.s8njee.com/csearch-api
    newName: registry.s8njee.com/csearch-api
    newTag: latest
