apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-config.yaml
  - cnpg-cluster.yaml
  - cnpg-pooler.yaml

configMapGenerator:
  - name: postgres-schema
    files:
      - 001-schema.sql

generatorOptions:
  disableNameSuffixHash: true
