apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-cluster-2-apollo
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: postgres-cnpg
    name: pg-cluster-2
  local:
    path: /var/lib/rancher/k3s/storage/pg-cluster-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - apollo
