---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: postgres-cnpg
spec:
  encryptedData:
    password: AgCPRtAP5WWtBHPjt5qPugYymUqcKvTkGylorSRTuEzSfWbrZWkle9n6A/CBQ/2LG4R6EnL7caJ0wCEVWeOpUSxDroOms9k9zzZ0LCOMx++lj87kQOUXRMd1dn8FAD4Npl/CbP9k3+GIvwtLVgkQ1BnYtFu+CRTu4qrvdGHh5R+ZRA3hc771qfipk61rzo07r70AEvwxQbZ1vMFvUiDNGcQLtG/C4Lp/AozFXc6i21mp2Rzn0GIO9iVx1Eu7P3pl3LV12YFsqYMzZvj8DxvT2WEOQ/vbSA3IC2eLdeEPsT9T72HmA6aXmKmxvzAkjbV61CMpSvdosJVRh8PuN3OfPeso3IXALphEY75tUvsHpavuJINiC9xBPad4rVF8WQUDbqlPujfwN6Y8N8ylevrfF4EnJOctruLxbsVFxuDizI1wzAOA8edrGxHiiaLbgkqyReTP6gi45X5zT+r5CivNnzP1XZLQFwTV8UcBehz6JyYfyEWd3KSI1Ojy9krT8RQqu2vtCqbK0J2PovClEJmoj2SvMXq0zCtxWGNTupSUX0bgWdA34xQZFzuB5bdEMzXeuKofIKwSVlRy11C929+4iu07upRkQAdxMY0mlNIfP6rbi5bk3l4zGPOtVXy2OI3Dn75WN9/bLsJRtybvxjVlvRaTGGItoyT3akqODrdh1zI+09EM3q5/WF/2yWw0haHgyC69YWcoT3iUYO055jXPJFZ9Jc2WVv6KJKhZ0l4H9KgAAw==
    username: AgAhv/r1H/BJ04FN19OlPIdHi3nWA2VpSZTvGPNr11eX5R4eBb/Cyf1MOrlp9szreJk8pcCMyj90N7g3mgj5FHgBZ2YsA0g2Vi5n689gV/OmnvIYsyr6gNGvR1wllfNZUD3o7aLrAXvMdeCxCglpVp7BJkFnbsIVFxjeDMQUKLsJRl3qPwlU6d7BKgtFW8WHRB6DaIgeYrjLx8Y+kozbt9m0OQMPvgAzr+K2p5qqvusKPTNaLvun5PmW2YcL3qjNoMwDmW+e3yI7h7JcYa/t1RldNzJBFnKIaDuGPDpHc26RYq3rqC2hFn3bdsYYtjjMVV3A0gaX39/5KvVxkSK14ziuWiIRMe0ZVC+H7r7p613K3nlvFX/bRnmnm34Um6qG0uWOeC3uSSCCRgSEdOUZf5vG2p9TcBQlfoHmEnjniWDl3BXNvGYtSyK/z8QNtj9N6SYTxHpGopGvc3JAfEX7tn4pqWBRbUwexAEmFrppbKejo6O2j3Xzu8GCRn5JMMLQ18cgwvftWAbT+8Ow452L6v0qJhEQxui9yaszD/ju6CbLceL2v5iVigtJFfyFNt0tZz+/a7LL1CSHQAzWE3aQktxWo+D2EM2Vu4y3yxSdUGBUho8ldDeS171JVAZ+DkZXUPlzbWzc9H8n8GQDOSg8HrmGzhRK5T2CqID4aPIoMBM4X/lUyhRhNdpzX3p0/Nm+sXOE/G7ijtiTYw==
  template:
    metadata:
      name: postgres-auth
      namespace: postgres-cnpg
    type: kubernetes.io/basic-auth
