---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB4geo1M4f9NQbKNE0On75LPrmmSV+nwqZfSYggo1kEXZ37A+tl851/H5iAb3NHAsIu6DIACFFhk3RjAJKflOdFV1yLfYkq174LjuyhrKoxXqGeWOisAoXKzyMRX0NAgIIbzdmfx2tIaYrno1cW9o6UfE8sL6+bGW2oF8bgb+U3lVvmA2esAMXLi5UfDcm43dveuVQHIwH/5N+Th+SxbNavOWMOTT+Pf1FKvrMbeTkX0Wfhwb6KvF5LP0dYCZhpCwBeZMBzbg7oHU1OcQtbp0RZXJ0RzGAotG4FI/ybzWmeYN5rIPDtGsb/mTsJWShI3y3oVXHIR+rYCtz/jQABU9Fhup5Yz6pJkL33qt6YYEJ65Ocn2Dnc21BLCwSlzP3QqoeBXgMc8tjljGdU0+HYVm2onQZwEdhMI28a1qrdJNpHn9/eDelKIkX4mRBMoRO9L7tbiXT7xuML9Xu6/MAY6qw3iH4SV4xPp3Oy8ChVJJkeUVMKS6DIkAGowZOJbjK4ebRT4HOx/lyoIIPHP8BHt/0ujsQaQUt0Y0j39NjxgMJn0kgIFblfslTq4udHq4MMvmBWxDuBxR4RdLCafstYZdBc80GWtLu/3hKRdD2Lh/iNaG4HatTkeZoNXGdm6Hc7eextSKBm6R3CXjvyLjGUzAjUgah49scRZ2z0l89eaCmlGUiK6MyQGKP8b/rOS+LV1Wjiwmeirp+Y+cPFN6CdwGsP32mlja06qS/YRyP5RnfnjQ==
  template:
    metadata:
      name: postgres-auth
      namespace: default
    type: Opaque
