apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-local
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/k8s/pvs/temp/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgrespvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi