

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/temp/postgres
    server: 10.0.0.3
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgrespvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  volumeName: postgres-pv
  resources:
    requests:
      storage: 30Gi
