// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package csearch

import (
	"database/sql"

	"github.com/tabbed/pqtype"
)

type Bill struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1973 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1974 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1975 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1976 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1977 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1978 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1979 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1980 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1981 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1982 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1983 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1984 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1985 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1986 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1987 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1988 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1989 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1990 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1991 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1992 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1993 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1994 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1995 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1996 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1997 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1998 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills1999 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2000 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2001 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2002 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2003 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2004 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2005 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2006 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2007 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2008 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2009 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2010 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2011 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2012 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2013 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2014 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2015 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2016 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2017 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2018 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2019 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2020 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2021 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2022 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2023 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2024 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2025 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2026 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2027 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}

type Bills2028 struct {
	Billid        sql.NullString
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      sql.NullString
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
}
