// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package csearch

import (
	"database/sql"
)

type Bill struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
	STs               interface{}
	HrTs              interface{}
	HconresTs         interface{}
	HjresTs           interface{}
	HresTs            interface{}
	SconresTs         interface{}
	SjresTs           interface{}
	SresTs            interface{}
	SearchDocument    interface{}
}

type BillAction struct {
	ID               int64
	Billtype         string
	Billnumber       string
	Congress         string
	ActedAt          string
	ActionText       sql.NullString
	ActionType       sql.NullString
	ActionCode       sql.NullString
	SourceSystemCode sql.NullString
}

type BillCommittee struct {
	Billtype      string
	Billnumber    string
	Congress      string
	CommitteeCode string
	CommitteeName sql.NullString
	Chamber       sql.NullString
}

type BillCosponsor struct {
	Billtype            string
	Billnumber          string
	Congress            string
	BioguideID          string
	FullName            sql.NullString
	State               sql.NullString
	Party               sql.NullString
	SponsorshipDate     sql.NullString
	IsOriginalCosponsor sql.NullBool
}

type BillSubject struct {
	Billtype   string
	Billnumber string
	Congress   string
	Subject    string
}

type Bills struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsHconre struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsHjre struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsHr struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsHre struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsSconre struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsSjre struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type BillsSre struct {
	Billid            sql.NullString
	Billnumber        string
	Billtype          string
	Introducedat      sql.NullString
	Congress          string
	SummaryDate       sql.NullString
	SummaryText       sql.NullString
	SponsorBioguideID sql.NullString
	SponsorName       sql.NullString
	SponsorState      sql.NullString
	SponsorParty      sql.NullString
	OriginChamber     sql.NullString
	PolicyArea        sql.NullString
	UpdateDate        sql.NullString
	LatestActionID    sql.NullInt64
	LatestActionDate  sql.NullString
	Statusat          string
	Shorttitle        sql.NullString
	Officialtitle     sql.NullString
}

type Vote struct {
	Voteid         string
	BillType       sql.NullString
	BillNumber     sql.NullString
	Congress       sql.NullString
	Votenumber     sql.NullString
	Votedate       sql.NullString
	Question       sql.NullString
	Result         sql.NullString
	Votesession    sql.NullString
	Chamber        sql.NullString
	SourceUrl      sql.NullString
	Votetype       sql.NullString
	SearchDocument interface{}
}

type VoteMember struct {
	Voteid      string
	BioguideID  string
	DisplayName sql.NullString
	Party       sql.NullString
	State       sql.NullString
	Position    string
}
