// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package csearch

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Bill struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1973 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1974 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1975 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1976 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1977 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1978 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1979 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1980 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1981 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1982 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1983 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1984 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1985 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1986 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1987 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1988 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1989 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1990 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1991 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1992 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1993 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1994 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1995 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1996 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1997 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1998 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills1999 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2000 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2001 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2002 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2003 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2004 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2005 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2006 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2007 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2008 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2009 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2010 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2011 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2012 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2013 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2014 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2015 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2016 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2017 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2018 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2019 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2020 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2021 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2022 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2023 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type Bills2024 struct {
	Billid        string
	Billnumber    string
	Billtype      string
	Introducedat  sql.NullString
	Congress      string
	Summary       pqtype.NullRawMessage
	Actions       pqtype.NullRawMessage
	Sponsors      pqtype.NullRawMessage
	Cosponsors    pqtype.NullRawMessage
	Statusat      string
	Shorttitle    sql.NullString
	Officialtitle sql.NullString
	Votes         pqtype.NullRawMessage
	STs           interface{}
	HrTs          interface{}
	HconresTs     interface{}
	HjresTs       interface{}
	HresTs        interface{}
	SconresTs     interface{}
	SjresTs       interface{}
	SresTs        interface{}
}

type User struct {
	Email     sql.NullString
	Firstname sql.NullString
	Lastname  sql.NullString
}

type Vote struct {
	Bill        pqtype.NullRawMessage
	Congress    sql.NullString
	Votenumber  sql.NullString
	Votedate    sql.NullString
	Question    sql.NullString
	Result      sql.NullString
	Votesession sql.NullString
	Yea         pqtype.NullRawMessage
	Nay         pqtype.NullRawMessage
	Present     pqtype.NullRawMessage
	Notvoting   pqtype.NullRawMessage
	Chamber     sql.NullString
	SourceUrl   sql.NullString
	Votetype    sql.NullString
	Voteid      string
}
