---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-api-openai
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgCtE1ZyNfghGq9Ij9MO2j8wXdZUYeduQOWh+yCxA59R2thg1WJSl4tJsJ4m9Wihh9tiu+GwPUijOwUGl7PjfV4c2HupJj3BMjuYuZuq0DyVlCfZF1AxOwyDs/YhN7/frHNdqxITVkr8MHiCQjU2SLYn6Z7N/jsHpr59mD7a5NxrLdfOV0omG131T5LdPrjnRkTVmYoM4WyLlDiIqd/joFvjKkQFfObgyboL0sEoNh+G7bFVlKNDq1WQFmuMRQyd46F0UPl0r/2BkKPLjg7ifNZUeefmM5ow8V9O9JmCqdaaXno9ooCMhy4C++jXBWrNMkVzlaqx75ibXUYHQJq+oPuBk04qJFNgjPjKagUFljuJsMHWqE4Nb+3s4E5X3KFxWOztNiYQfiJDz2ViKZgOQdKktpl5cmTi3KODEDKhVtocVxqfxsmBH2Sp+ixO+3TJJpYglIN9E/R134X7jcUaz22MoGEYr+9skmhTbQv0IiVnw9f31yQnWK68X7quO/cfbGlDdLd0LdSGXEDYKe0a8QqWKuvX/L3D2adIfi9bgFq/RvYUamvZJK2qshygzEUari48X3Um53mc9Yf2pa1Z3ndyigRzK/IPEcTHerz1mnsFN9kg3vjx19JXAtJmjll1qlu+WvwQg5CPQLWNF1DUEyX7kEWlxGWaSilBgs7Gcc0Hw3i021r2glx1I0twO4+3botYV6sZlff8m+7bqg==
  template:
    metadata:
      name: csearch-api-openai
      namespace: default
