---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csearch-api-openai
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgCbarmmJwJBbIMXizY8MBUIueCv6OGyKDr9N4KoRRFveepOhFiWELkdFkl2f7euc46BuO5Yei2cudCzyvVFz8aErhlIIhD/7BneRsWRRjnA5J4Xms28KSKnuy4cBy+7ReGp/5DFZ0eCO864ZmKpsL+iF/840B/uxhtRICBiChqpvIrvSSEojIY/VKnIsor+kbNuNje7H2ZKeA2I070+iA+2gJOSotGr/XNdsLrvMOf1LwFIwEoCm69FDyxubz4nNtmOOaQpDakQDrdmI/h7Z2+nVR9PBlPvkIeVMMHWxqHF8abmChRv5fkVxDw5HGEejHFQpGhMP90cOClEM9/OS4heLSUzezXolOeSJA7ta8HDZIw9CH6uCF3M3WF75MAowUIglfEC76gfmsHGO4i7/CDVyxfVHnR1fWk2yCqva+iStXhBOZRSt368fJt++kpWiY7Eb8qw8ZACQf3Dx4qGjw61RluxYk7+8Fdpt6ZrWwsbsJjsgVGsOks07LjIZp93FAW/kkYUr6E2Lg1USJd3thi5trVsoompDnpk1SmPz+kA55sRFv1KejTQQCyOEJg+mRKVoqcK/+iiW1F0MPoaYGVg7XFroQq+ctU3kfBSIDu/p8X0sYol2snBXYXt5feGI6Fo8KXyjFKvJYDXI1t0OEPL0C+WZe3ZkPqX/ZiVVxwNzWZ+0pFB4KJ8oLxUm6ezMOUwMjfNIp9c2K0rkDjEfBuDIUWqPjfiQH0J0RCXqx8JZkHVbcdWLnhi1GA0dsHXFgs3FjcyWOo70qqd61w272VJvQpfsY5ZjZ2mnCxtzYD+JICfZ3qggv68LuTdRO18qBUTvEF5GRTxJq3zM8N671/5z+sd3uO5iXRdmHNQrseEp2Q/aaeIJ3mU9mblw77lYCHQj4tkEwTv6x0JrM07oI/8nZFsUg==
  template:
    metadata:
      name: csearch-api-openai
      namespace: default
