apiVersion: v1
kind: Service
metadata:
  name: csearch-frontend-lb
  labels:
    app.kubernetes.io/name: csearch-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: mars
spec:
  selector:
    app.kubernetes.io/name: csearch-frontend
  ports:
    - name: http
      port: 4200
      targetPort: http
  type: LoadBalancer
