apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - api-lb.yaml
  - redis.yaml
  - scraper.yaml
  - frontend.yaml
  - frontend-lb.yaml

images:
  - name: registry.s8njee.com/csearch-api
    newName: registry.s8njee.com/csearch-api
    newTag: 7f7b185c16a8fcbf35bff56ddfc8a8c73fbba7c3
  - name: registry.s8njee.com/csearch-updater
    newName: registry.s8njee.com/csearch-updater
    newTag: 7f7b185c16a8fcbf35bff56ddfc8a8c73fbba7c3
  - name: registry.s8njee.com/csearch-frontend
    newName: registry.s8njee.com/csearch-frontend
    newTag: 7f7b185c16a8fcbf35bff56ddfc8a8c73fbba7c3
