apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - api-lb.yaml
  - redis.yaml
  - scraper.yaml
  - frontend.yaml
  - frontend-lb.yaml

images:
  - name: registry.s8njee.com/csearch-api
    newName: registry.s8njee.com/csearch-api
    newTag: c10faa1ac3255468758543a8a9c4e00a35c614f2
  - name: registry.s8njee.com/csearch-updater
    newName: registry.s8njee.com/csearch-updater
    newTag: c10faa1ac3255468758543a8a9c4e00a35c614f2
  - name: registry.s8njee.com/csearch-frontend
    newName: registry.s8njee.com/csearch-frontend
    newTag: c10faa1ac3255468758543a8a9c4e00a35c614f2
