apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - api-lb.yaml
  - redis.yaml
  - scraper.yaml
  - frontend.yaml
  - frontend-lb.yaml
  - csearch-api-openai-sealedsecret.yaml

images:
  - name: registry.s8njee.com/csearch-fastapi
    newName: registry.s8njee.com/csearch-fastapi
    newTag: f7285bb8037447e39f82e5fb1a614bbf270f70d3
  - name: registry.s8njee.com/csearch-updater
    newName: registry.s8njee.com/csearch-updater
    newTag: f7285bb8037447e39f82e5fb1a614bbf270f70d3
  - name: registry.s8njee.com/csearch-frontend
    newName: registry.s8njee.com/csearch-frontend
    newTag: f7285bb8037447e39f82e5fb1a614bbf270f70d3
