apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
spec:
  selector:
    app: postgres-dev
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      containers:
        - name: postgres
          # Uses the custom built image that contains schema.sql in /docker-entrypoint-initdb.d/
          image: registry.s8njee.com/csearch-postgres:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: csearch
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
