apiVersion: v1
kind: PersistentVolume
metadata:
  name: congress-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: freya.local
    path: /mnt/raid6/k8s/congress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: congress-nfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: congress-nfs-pv
